# Dockerの定義

services:
  # http://localhost:3000/でReactアプリにアクセスするのに使用
  react-app:
    build:
      context: .
      dockerfile: ./react-app/Dockerfile
    environment:
      - NODE_ENV=production
    command: npm run build && npm install -g serve && serve -s build
    ports:
      - "3000:3000"
    volumes:
      - ./react-app:/homepage/react-app
      - /homepage/react-app/node_modules

  # http://localhost:8000/でAPIにアクセスするのに使用
  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - PYTHONPATH=/app/backend
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    working_dir: /app
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --workers 4

  # PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # http://localhost:8080/でデータベースの内容を確認するのに使用
  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  db_data:
