# 開発環境用
# docker compose -f docker-compose.dev.yml up -d --build で実行

version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: ./react-app/Dockerfile.dev
    volumes:
      - ./react-app:/app/react-app
      - /app/react-app/node_modules
    environment:
      - SKIP_PREFLIGHT_CHECK=true
      - NODE_OPTIONS=--openssl-legacy-provider
    command: npm start
    ports:
      - "3000:3000"
    restart: always

  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    user: "${UID}:${GID}"  # ホストのユーザーIDとグループIDを使用
    environment:
      - PYTHONPATH=/app/backend
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1  # .pycファイルを生成しない
    command: >
      uvicorn backend.main:app
      --host 0.0.0.0
      --port 8000
      --reload
    volumes:
      - ./backend:/app/backend
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      db:
        condition: service_healthy

  # PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Adminer
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

volumes:
  db_data:
