# Dockerの定義
# 本番環境用
# ローカルマシンで
# cd react-app
# npm install
# npm run build
# rsync -avz --delete build/ maru@$SSH_IP:/var/www/homepage_new/react-app/build/
# を実行

# 本番環境で
# cd /var/www/homepage_new
# docker compose up -d --build

services:
  # http://localhost:3000/でReactアプリにアクセスするのに使用
  react-app:
    build:
      context: ./react-app
      dockerfile: Dockerfile
      args:
        - BUILD_PATH=./build
    environment:
      - NODE_OPTIONS=--max-old-space-size=8192
    ports:
      - "3000:80"
    restart: always
    networks:
      - app-network

  # http://localhost:8000/でAPIにアクセスするのに使用
  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    environment:
      - PYTHONPATH=/app/backend
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./backend/alembic.ini:/app/alembic.ini
      - ./backend/alembic:/app/alembic
    working_dir: /app
    command: >
      uvicorn backend.main:app
      --host 0.0.0.0
      --port 8000
      --workers 1
      --proxy-headers
      --log-level debug
    restart: always
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # PostgreSQL
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Tokyo
      PGTZ: Asia/Tokyo
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    healthcheck:  # ヘルスチェックを追加
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  # http://localhost:8080/でデータベースの内容を確認するのに使用
  adminer:
    image: adminer
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
