# 都市名・都道府県名を英語名にマッピングする辞書
CITY_MAPPING = {
    "東京都": "Tokyo",
    "大阪府": "Osaka",
    "福岡県": "Fukuoka",
    "北海道": "Hokkaido",
    "宮城県": "Miyagi",
    "愛知県": "Aichi",
    "広島県": "Hiroshima",
    "沖縄県": "Okinawa",
    "千葉県": "Chiba",
    "神奈川県": "Kanagawa",
    "埼玉県": "Saitama",
    "京都府": "Kyoto",
    "兵庫県": "Hyogo",
    "奈良県": "Nara",
    "滋賀県": "Shiga",
    "和歌山県": "Wakayama",
    "三重県": "Mie",
    "岐阜県": "Gifu",
    "静岡県": "Shizuoka",
    "山梨県": "Yamanashi",
    "長野県": "Nagano",
    "新潟県": "Niigata",
    "富山県": "Toyama",
    "石川県": "Ishikawa",
    "福井県": "Fukui",
    "茨城県": "Ibaraki",
    "栃木県": "Tochigi",
    "群馬県": "Gunma",
    "山形県": "Yamagata",
    "秋田県": "Akita",
    "岩手県": "Iwate",
    "青森県": "Aomori",
    "福島県": "Fukushima",
    "鳥取県": "Tottori",
    "島根県": "Shimane",
    "岡山県": "Okayama",
    "山口県": "Yamaguchi",
    "香川県": "Kagawa",
    "徳島県": "Tokushima",
    "愛媛県": "Ehime",
    "高知県": "Kochi",
    "佐賀県": "Saga",
    "長崎県": "Nagasaki",
    "熊本県": "Kumamoto",
    "大分県": "Oita",
    "宮崎県": "Miyazaki",
    "鹿児島県": "Kagoshima"
}

# 都道府県のリスト
PREFECTURE_LIST = [
    "北海道",
    "青森県",
    "岩手県",
    "宮城県",
    "秋田県",
    "山形県",
    "福島県",
    "茨城県",
    "栃木県",
    "群馬県",
    "埼玉県",
    "千葉県",
    "東京都",
    "神奈川県",
    "新潟県",
    "富山県",
    "石川県",
    "福井県",
    "山梨県",
    "長野県",
    "岐阜県",
    "静岡県",
    "愛知県",
    "三重県",
    "滋賀県",
    "京都府",
    "大阪府",
    "兵庫県",
    "奈良県",
    "和歌山県",
    "鳥取県",
    "島根県",
    "岡山県",
    "広島県",
    "山口県",
    "徳島県",
    "香川県",
    "愛媛県",
    "高知県",
    "福岡県",
    "佐賀県",
    "長崎県",
    "熊本県",
    "大分県",
    "宮崎県",
    "鹿児島県",
    "沖縄県"
]