"""add sequence to types table

Revision ID: 1bd41ab9b2ef
Revises: 4bc3f0e826eb
Create Date: 2025-02-26 14:48:43.889178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd41ab9b2ef'
down_revision: Union[str, None] = '4bc3f0e826eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_employees_employee_no'), 'employees', ['employee_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_employee_no'), table_name='employees')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    # ### end Alembic commands ###
