"""掲示板用のモデル作成

Revision ID: 44a415b2bb36
Revises: d6a54a5de199
Create Date: 2025-03-16 05:14:43.697855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44a415b2bb36'
down_revision: Union[str, None] = 'd6a54a5de199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulletin_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulletin_posts_id'), 'bulletin_posts', ['id'], unique=False)
    op.create_table('bulletin_cells',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulletin_id', 'row', 'col', name='uix_cell_position')
    )
    op.create_index(op.f('ix_bulletin_cells_id'), 'bulletin_cells', ['id'], unique=False)
    op.create_table('bulletin_column_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('col', sa.Integer(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulletin_id', 'col', name='uix_column_dimension')
    )
    op.create_index(op.f('ix_bulletin_column_dimensions_id'), 'bulletin_column_dimensions', ['id'], unique=False)
    op.create_table('bulletin_merges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('start_row', sa.Integer(), nullable=False),
    sa.Column('start_col', sa.Integer(), nullable=False),
    sa.Column('end_row', sa.Integer(), nullable=False),
    sa.Column('end_col', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulletin_merges_id'), 'bulletin_merges', ['id'], unique=False)
    op.create_table('bulletin_row_dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bulletin_id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['bulletin_id'], ['bulletin_posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bulletin_id', 'row', name='uix_row_dimension')
    )
    op.create_index(op.f('ix_bulletin_row_dimensions_id'), 'bulletin_row_dimensions', ['id'], unique=False)
    op.create_table('cell_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_id', sa.Integer(), nullable=False),
    sa.Column('font_bold', sa.Boolean(), nullable=True),
    sa.Column('font_color', sa.String(length=16), nullable=True),
    sa.Column('font_size', sa.Float(), nullable=True),
    sa.Column('bg_color', sa.String(length=16), nullable=True),
    sa.Column('border_top_style', sa.String(length=16), nullable=True),
    sa.Column('border_top_color', sa.String(length=16), nullable=True),
    sa.Column('border_right_style', sa.String(length=16), nullable=True),
    sa.Column('border_right_color', sa.String(length=16), nullable=True),
    sa.Column('border_bottom_style', sa.String(length=16), nullable=True),
    sa.Column('border_bottom_color', sa.String(length=16), nullable=True),
    sa.Column('border_left_style', sa.String(length=16), nullable=True),
    sa.Column('border_left_color', sa.String(length=16), nullable=True),
    sa.Column('alignment_horizontal', sa.String(length=16), nullable=True),
    sa.Column('alignment_vertical', sa.String(length=16), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['bulletin_cells.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_id')
    )
    op.create_index(op.f('ix_cell_styles_id'), 'cell_styles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cell_styles_id'), table_name='cell_styles')
    op.drop_table('cell_styles')
    op.drop_index(op.f('ix_bulletin_row_dimensions_id'), table_name='bulletin_row_dimensions')
    op.drop_table('bulletin_row_dimensions')
    op.drop_index(op.f('ix_bulletin_merges_id'), table_name='bulletin_merges')
    op.drop_table('bulletin_merges')
    op.drop_index(op.f('ix_bulletin_column_dimensions_id'), table_name='bulletin_column_dimensions')
    op.drop_table('bulletin_column_dimensions')
    op.drop_index(op.f('ix_bulletin_cells_id'), table_name='bulletin_cells')
    op.drop_table('bulletin_cells')
    op.drop_index(op.f('ix_bulletin_posts_id'), table_name='bulletin_posts')
    op.drop_table('bulletin_posts')
    # ### end Alembic commands ###
