"""departmentにsort追加

Revision ID: 6b0a1ff6bf70
Revises: 4bc3f0e826eb
Create Date: 2025-03-09 06:50:49.037708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b0a1ff6bf70'
down_revision: Union[str, None] = '4bc3f0e826eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('sort', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_employees_employee_no'), 'employees', ['employee_no'], unique=True)
    op.alter_column('types', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('types_id_seq'::regclass)"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('types', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('types_id_seq'::regclass)"))
    op.drop_index(op.f('ix_employees_employee_no'), table_name='employees')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_column('departments', 'sort')
    # ### end Alembic commands ###
