"""アラーム関係のリレーション追加

Revision ID: 85f6f40a7b55
Revises: deb7b2bec852
Create Date: 2025-05-31 12:12:10.700996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f6f40a7b55'
down_revision: Union[str, None] = 'deb7b2bec852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
