"""employee, department作成

Revision ID: af952fac3d0b
Revises: 
Create Date: 2024-11-16 15:24:20.089745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af952fac3d0b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_employee_no', table_name='employees')
    op.drop_index('ix_employees_id', table_name='employees')
    op.drop_index('ix_employees_name', table_name='employees')
    op.drop_table('employees')
    op.drop_table('employee_department')
    op.drop_index('ix_depertments_id', table_name='depertments')
    op.drop_index('ix_depertments_name', table_name='depertments')
    op.drop_table('depertments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depertments',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('depertments_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='depertments_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_depertments_name', 'depertments', ['name'], unique=False)
    op.create_index('ix_depertments_id', 'depertments', ['id'], unique=False)
    op.create_table('employee_department',
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['depertments.id'], name='employee_department_department_id_fkey'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], name='employee_department_employee_id_fkey'),
    sa.PrimaryKeyConstraint('employee_id', 'department_id', name='employee_department_pkey')
    )
    op.create_table('employees',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('employee_no', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='employees_pkey')
    )
    op.create_index('ix_employees_name', 'employees', ['name'], unique=False)
    op.create_index('ix_employees_id', 'employees', ['id'], unique=False)
    op.create_index('ix_employees_employee_no', 'employees', ['employee_no'], unique=True)
    # ### end Alembic commands ###
