"""掲示板モデルのセルの背景色などを変更

Revision ID: cb7ccf5d59c0
Revises: 039430cfc45a
Create Date: 2025-03-16 07:30:43.156781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb7ccf5d59c0'
down_revision: Union[str, None] = '039430cfc45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
