"""加工機関係のモデル追加

Revision ID: cf7bc4d1faf5
Revises: 37e83ad3bd65
Create Date: 2025-05-31 06:28:52.002535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf7bc4d1faf5'
down_revision: Union[str, None] = '37e83ad3bd65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lines_id'), 'lines', ['id'], unique=False)
    op.create_index(op.f('ix_lines_name'), 'lines', ['name'], unique=False)
    op.create_table('tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_id'), 'tools', ['id'], unique=False)
    op.create_index(op.f('ix_tools_name'), 'tools', ['name'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort', sa.Integer(), nullable=True),
    sa.Column('line_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_machines_id'), 'machines', ['id'], unique=False)
    op.create_index(op.f('ix_machines_name'), 'machines', ['name'], unique=False)
    op.create_table('tool_nos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('register_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('machine_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tool_nos_id'), 'tool_nos', ['id'], unique=False)
    op.create_index(op.f('ix_tool_nos_name'), 'tool_nos', ['name'], unique=False)
    op.create_table('tool_tool_no',
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('tool_no_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tool_no_id'], ['tool_nos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tool_id', 'tool_no_id')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=True)
    op.create_index(op.f('ix_employees_employee_no'), 'employees', ['employee_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_employee_no'), table_name='employees')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('tool_tool_no')
    op.drop_index(op.f('ix_tool_nos_name'), table_name='tool_nos')
    op.drop_index(op.f('ix_tool_nos_id'), table_name='tool_nos')
    op.drop_table('tool_nos')
    op.drop_index(op.f('ix_machines_name'), table_name='machines')
    op.drop_index(op.f('ix_machines_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_tools_name'), table_name='tools')
    op.drop_index(op.f('ix_tools_id'), table_name='tools')
    op.drop_table('tools')
    op.drop_index(op.f('ix_lines_name'), table_name='lines')
    op.drop_index(op.f('ix_lines_id'), table_name='lines')
    op.drop_table('lines')
    # ### end Alembic commands ###
