"""設備位置情報追加

Revision ID: deb7b2bec852
Revises: a42ce147f31d
Create Date: 2025-05-31 12:09:16.995376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'deb7b2bec852'
down_revision: Union[str, None] = 'a42ce147f31d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('position_x', sa.Integer(), nullable=True))
    op.add_column('lines', sa.Column('position_y', sa.Integer(), nullable=True))
    op.alter_column('lines', 'name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.add_column('machines', sa.Column('position_x', sa.Integer(), nullable=True))
    op.add_column('machines', sa.Column('position_y', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('machines', 'position_y')
    op.drop_column('machines', 'position_x')
    op.alter_column('lines', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('lines', 'position_y')
    op.drop_column('lines', 'position_x')
    # ### end Alembic commands ###
