"""掲示板モデルのセルの背景色などを変更

Revision ID: e2a4d553f1d1
Revises: 039430cfc45a
Create Date: 2025-03-16 08:10:44.361785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a4d553f1d1'
down_revision: Union[str, None] = '039430cfc45a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
